// Generated by CoffeeScript 1.6.3
/*
Message Model
*/


(function() {
  var Message, ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  Message = new Schema({
    _id: ObjectId,
    user: {
      type: ObjectId,
      ref: 'User'
    },
    content: String,
    createTime: {
      type: Date,
      "default": new Date()
    }
  });

  module.exports = mongoose.model('Message', Message);

}).call(this);

/*
//@ sourceMappingURL=message.map
*/
